prog:personnage.o main.o stage.o entitersecondaire.o background.o jeu.o scrolling.o collision.o manette.o enigme.o anim.o options.o pre_menu.o gestion.o sous_menu.o
	gcc personnage.o main.o stage.o entitersecondaire.o background.o jeu.o scrolling.o collision.o manette.o enigme.o anim.o options.o pre_menu.o gestion.o sous_menu.o -o prog -g -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx -g
main.o:main.c
	gcc -c main.c  -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
stage.o:stage.c
	gcc -c stage.c  -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
personnage.o:personnage.c
	gcc -c personnage.c  -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
entitersecondaire.o:entitersecondaire.c
	gcc -c entitersecondaire.c  -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
background.o:background.c
	gcc -c background.c  -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
jeu.o:jeu.c
	gcc -c jeu.c  -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
scrolling.o:scrolling.c
	gcc -c scrolling.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
collision.o:collision.c
	gcc -c collision.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
manette.o:manette.c
	gcc -c manette.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
enigme.o:enigme.c
	gcc -c enigme.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
options.o:options.c
	gcc -c options.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
pre_menu.o:pre_menu.c
	gcc -c pre_menu.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
anim.o:anim.c
	gcc -c anim.c 	-lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
gestion.o:gestion.c
	gcc -c gestion.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
sous_menu.o:sous_menu.c
	gcc -c sous_menu.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL_gfx
